@startuml
'title: Worttrainer Reloaded - kbauer'

class Model {
  -dataList : List<Data>
  -auswahl : Data
  -path : String
  +getDataList() : List<Data>
  +setDataList(List<Data>) : void
  +getRandomData() : Data
  +getSpecificData(int) : Data
  +addData(Data) : void
  +removeData(Data) : void
  +getAuswahl() : Data
  +setPath(String) : void
  +getPath() : String
  +addDataToJson(Data) : void
  +readDataFromJson() : List<Data>
  +compareData(List<Data>) : boolean
  +clearPersistence() : void
}

class Data {
  -wort : String
  -url : String
  +addName(String) : void
  +checkName(String) : boolean
  +addUrl(String) : boolean
  +addUrl(URL) : void
  +checkUrl(String) : boolean
  +getUrl() : URL
  +getName() : String
  +toString() : String
  +equals(Object) : boolean
}

class View {
}

class Controller {
  -model : Model
  -view : View
}

Controller --> Model
Controller --> View
Model --> Data

@enduml
