@startuml
|Benutzer|
start
:Webapp öffnen;
:Registrieren oder Anmelden;

if (Brewit gekauft?) then (Ja)
    :Zugriff auf alle Funktionen;
    :Rezept erstellen und teilen;
    :Rezept von anderen laden;
    :Brauprozess starten;
    :Brauprozess überwachen;
else (Nein)
    :Brewit im Shop kaufen;
    :Bestellbestätigung erhalten;
endif

stop
|Webapp|
start
:Benutzerverwaltung;
:Zugriff auf Rezept-Datenbank;
if (Rezept erstellt?) then (Ja)
    :Rezept speichern;
    :Rezept teilen;
endif
stop

|Brewit (Maschine)|
start
:Rezept empfangen;
:Brauprozess starten;
:Sensoren überwachen;
:Status an Webapp senden;
stop
@enduml
