@startuml
'title: Worttrainer Reloaded - kbauer'

class Model {
  +dataList : List<Data>
  +getDataList() : List<Data>
  +setDataList(dataList : List<Data>)
  +addData(Data) : void
  +removeData(Data) : void
}

class Data {
  +wort : String
  +url : String
  +checkURL(String url) : boolean
}

class View {
  +displayData()
  +updateView()
}

class Controller {
  +model : Model
  +view : View
  +updateModel(data : String)
  +notifyView()
}

Controller --> Model
Controller --> View
Model --> Data

@enduml
